import type { Metadata } from "next";

import "./globals.css";

import Navbar from "./components/navbarmenu/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "CardBazzar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">{children}</main> {/* Hauptinhalt */}
        <Footer />
      </body>
    </html>
  );
}
